'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const vm=require('node:vm');

let feed=null;
const window={AetherionUpdater:{receiveChannel(value){feed=value}}};
vm.runInNewContext(fs.readFileSync('channel.js','utf8'),{window},{filename:'channel.js'});
assert(feed,'channel did not deliver a release');
assert.equal(feed.schema,2);assert.equal(feed.channel,'stable');
assert.equal(feed.release.version,'1.72.5');assert.equal(feed.release.build,194);
assert.equal(feed.release.minimumBundled,'1.72.4');assert.equal(feed.release.requiresApk,true);
assert.equal(feed.release.modules.length,1);assert.deepEqual(Object.keys(feed.release.assets),[]);
const entry=feed.release.modules[0];
assert.equal(entry.id,'v175-native-install-path');
assert.equal(entry.sha256,crypto.createHash('sha256').update(entry.source).digest('hex'));
assert.match(entry.source,/const VERSION='1\.72\.5'/);assert.match(entry.source,/const ANDROID_BUILD=194/);
assert.match(entry.source,/assets\/v175\/native-build-194\.json/);
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
assert.equal(feed.release.apkUrl,manifest.android_apk.url);assert.equal(feed.release.apkSha256,manifest.android_apk.sha256);assert.equal(feed.release.apkSize,manifest.android_apk.size);
assert.match(feed.release.apkUrl,/v1\.72\.5\/Aetherion_Reforged_v1\.72\.5_MODULAR_EQUIPMENT_UPDATE\.apk$/);
assert(fs.statSync('channel.js').size<=100000);
assert(feed.release.notes.some(note=>note.includes('17 equipment slots')));
assert(feed.release.notes.some(note=>note.includes('startup-crash repair')));

let capture=null,prevented=0,stopped=0;
const location={href:'https://appassets.androidplatform.net/assets/game/index.html'};
const legacyWindow={AetherionUpdater:{receiveChannel(){}},__aetherionFullApkUrl:null};
const document={addEventListener(type,handler,useCapture){if(type==='click'&&useCapture)capture=handler}};
vm.runInNewContext(fs.readFileSync('channel.js','utf8'),{window:legacyWindow,document,location},{filename:'channel.js'});
assert.equal(typeof capture,'function','legacy full-APK handoff was not installed');
capture({target:{closest(){return{textContent:'DOWNLOAD FULL APK'}}},preventDefault(){prevented++},stopPropagation(){stopped++},stopImmediatePropagation(){stopped++}});
assert.equal(location.href,feed.release.apkUrl,'legacy update center was not redirected to build 194');
assert.equal(prevented,1);assert.equal(stopped,2);
console.log('v1.72.5 channel: exact build-194 handoff, APK metadata, legacy-button redirect, modular notes, and size limit passed');
